name: mi_entorno
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - opencv
  - dlib
  - postgresql
  - psycopg2  # Instalado via conda en lugar de pip
  - sqlalchemy
  - alembic
  - pip:
    - face_recognition
    - flask
    - opencv-python
    - python-dotenv